## The Basketball Sharpe Ratio: Risk Adjusting Excess Points
---
*Kiran Krishnamurthi*

*February 2023*

If you've been following the NBA over the past few years, you'll be well aware of the scoring "inflation" that has taken place across the league. Gone are the days where being a 20+ points-per-game (PPG) scorer could get you an all-star nomination. Going back 10-years to the 2012-2013 NBA season, nine players averaged 20+ points-per-game. Go back five years to the 2017-2018 NBA season and you'll see 23 players averaged 20+ points-per-game. An in today's league for the 2022-2023 NBA season, a whoping 38 players are average 20+ points-per-game. In the past decade, the league has seen a 322% increase in 20+ point-per-game scorers. Sure, 20 is an arbitrary benchmark for someone who's considered a good scorer, but it goes to show the proliferation of points in today's league. 

While there are a host of factors that have given way to the scoring explosion over the past decade, free throws have always been a point of interest to me. Stephen Curry is one of the generation's elite scorers, and I've always admired his ability to create his own points off the dribble, meaning Steph can get buckets whenever he wants through his ability to get to the hoop, put up threes, or pop a mid-range jumper. In other words, Steph isn't realiant on the free-throw line or getting foul calls to get his points, or at least I'm of this belief. On the other hand, I can't help but think about Harden's MVP caliber years in Houston as being *heavily* reliant on getting foul calls on baited drivers and three-pointers. Harden generated historic scoring numbers during his MVP season, and to his credit he proved that he's one of the greatest to ever do it. But, his season stats prompted me to dig further into the source and value of his points. Basketball fans will know that despite Harden's massive offensive contribution, he dissapeared in the biggest moments and remains one of the 21st century MVPs without a NBA championship. Therefore, I'm left asking the question: **is there a better way to measure a player's offensive value besides pure PPG numbers?** 

Over the past semester I've gotten the chance study and work on problems in quantitative finance, leaving me with an interest to apply principles and concepts from this realm into other domains where applicable. One of the simplest but most influential contributions in this space is the Sharpe Ratio. The Sharpe Ratio, for those who aren't familiar with this concept, is an asset or portfolio performance metric created by William Sharpe back in 1996. This metric compares an investment's return with its risk, based on the belief that higher excess returns may come with greater volatility and risk over the same timeframe. When it comes to investing strategy, the Sharpe Ratio can be understood as a risk-adjusted performance metric to compare investing skill. 

$$ Sharpe = \frac{\mu_{i} - r_f}{\sigma_{i}} $$

The two components of the Sharpe Ratio that pique my interest in using it explain better offensive output in the NBA are (1) excess returns and (2) return volatility. Excess returns in finance are measured by the actual return on an assets minus the risk-free return. The risk-free return is simply the expected return on an asset with zero risk. While there's no truly risk-free asset, most investors treat this so called "risk-free rate" as the rate of return they expected at minimum from parking their money somewhere, most likely being the safest or lowest risk asset out there. This is often represented through the rate of return on short-term government bonds.

I liken this back to basketball by considering risk-free points as free-throw attempts. A free-throw is quite literally a chance at "free" points. We can solve one of the original problems I had with understanding a player's offensive value by distilling their points scored from those points that came through free-throws. Free-throw attempts and makes aren't the same idea, but if you're a player getting a lot of free-throw attempts you should be expected to produce more points since you're given more chances at "free" points. Most investors will adopt the same risk-free rate but not all basketball players have the same amount of free-throw attempts per game, but makes the concept of "excess points" something unique and specific to each player. 

The second concept from the Sharpe Ratio which I connect back to basketball is return volatility. This should be more straightforward, but it is just the measure of an asset's standard deviation over some timeframe. To put this in a basketball context, I treat this component of the Sharpe Ratio as the standard deviation of a player's points-per-game over an NBA season.

$$ B = \frac{\mu_{ppg} - \mu_{fta}}{\sigma_{ppg}} $$

Above I represent the translated Sharpe Ratio into basketball ($B$) terms. The rest of this paper looks into the behaviour of this metric over the past handful of NBA seasons and trys to show a more accurate understanding of a player's offensive value compared to their raw PPG numbers. 

### James Harden and the 2017-2018 NBA Regular Season

#### How much do free throw attempts impact Harden's scoring?

![harden_dual_plot](james_harden_dual_plot.png)


The above two plots take a closer look into James Harden's scoring output during his MVP season. There is no doubt he put up an MVP worthy performance, with multiple 50+ point games in the era before the scoring explosion that we're currently experience. However, the closer examination does reveal that across the season, Harden's "risk-free" (free throw attempts) points accounted for 35% of his total points-per-game. This number doesn't mean too much on it's own, but it does allow us to understand that perhaps on any given night, 35% of James Harden's points could be coming from the free-throw line.

Another takeaway from the dual plot above would be the understanding in the relationship between massive scoring performances and total free throw attempts. An inital hypothesis I had when approaching this project was whether Harden's massive MVP-caliber scoring nights came from a disproportionate amount of free throw attempts. While I'm not testing for any statistical significance in evaluating this idea, the eye test suggests otherwise. It seems the big scoring nights from Harden aren't as heavily influenced by his trips to the free-throw line as some of his other nights. 

Finally, it would appear that Harden's reliance on the charity stripe to get points increases throughout the NBA season. The plot on the right is a time-series plot of the "share" of points that Harden scored that could've potentially come from the free-throw line (measured by total free throw attempts), and it suggests a slight positive trend from the start to the end of the season. The plot on the left showing his nightly free throw attempts may also provide better visual evidence as to the increase across the season. This finding is important insofar as perhaps Harden's MVP campaign is bolstered by his ability to foul-bait and receive calls as the season progressed. Or, maybe it gives into the idea that the better players get calls; as Harden built up a name for himself as the league's best scorer, he started to receive more favorable calls from the refs. Regardless, Harden's average free throw attempts per game clearly crept up along with his MVP odds. 

#### Applications on the Top 30 Scorers from the 2017-2018 Season

![joint_sharpe_plot](joint_sharpe_plots_for_1718.png)

By decomposing the $B$ and plotting the numerator on the x-axis and the denominator on the y-axis, we can better understand where the discrepancies arrive between players and their respective $B$. I broke the plot up into four quadrants, which we can treat like we would quadrants on a typical x,y coordinate plane. Quadrant one is the top right corner and then moving counter clockwise the following three quadrants are labeled. The best quadrant to be in is quadrant 4, also understood as the bottom right quadrant in the above plot. Players in quadrant four exhibit higher excess points and lower volatility in their scoring. They can be considered the most consistent performers given their low volatility as well as some of the most efficient performers given their lack of reliance on free throws to get points.  

Quadrant four is home to only 4 players, and 1 on the border. CJ McCollum, Victor Oladipo, Giannis Antetokounmpo, and Klay Thompson are the four players from the 2017-2018 season who slide into this position. Kevin Durant is on the border. Our MVP, James Harden, finds himself in quadrant one. Despite Harden's reliance on the free throw line to get his points, he still such an offensive weapon that even when we take out his free throw attempts from nightly points per game, he still is amongst the league's best scorers. However, a big driver of his positioning in this chart is the scoring volatility. Referencing the first plot, it becomes clear that Harden has a lot of ups and downs to his scoring, with the nightly output somewhere in the range of 20 to 60 (more realistically 25 - 45) points. 

The chart shows that Harden has a scoring volatility $\sigma_{ppg}$ of ~9.25. He's only outmatched by Anthony Davis as the most volatile scorer during this season, which does have implications for a head coach or a GM. Some of the decisions or questions that come to mind when looking at the plot would be how much can I trust my superstar depending on what quadrant they land in? For a head coach, trying to run your offense through a player in quadrants one or four makes sense given that their amongst the league's best scorers. But, at the same time, when your player has points-per-game range of nearly 20 (one standard deviation above/below the mean), then you're at risk for an offensive collapse or meltdown if they can't get it going. Obviously a team would not put all their eggs in one basket and most likely trust the offense from other players. Nonetheless, I see this as more of a consideration to make when offering someone a max contract, because will they really be that guy all season if their scoring is so volatile? 

When it comes to evaluating the talent out there during that 2017-2018 NBA season, this chart would suggest that LeBron James or Kevin Durant were "better" scorers when taking the quality of offense into account. Both LeBron and Durant are more consistent in their scoring with lower volatility, but still manage to put up the same amount of excess points (or more) than Harden. They might not have dominated the press with flashy 60-point games, but they were consistent throughout the season-- perhaps a big reason why the two of them met in the NBA finals whereas Harden all but dissapeared during the Western Conference Finals. 

Finally, but maybe my favorite, takeaway from this season's $B$ analysis would be understanding the greatness that is Klay Thompson. Figure 2, which plots players' $B$, shows that Klay has undoubtedly the highest $B$ out of all players that season. Klay's greatness does not come in the form of a player who a team would run their offense through, but instead comes through his consistency and control over his own output. Klay has the 3rd lowest scoring volatility out of the top 30 scorers from that season, but still remains in the half of players in terms of excess points. What's even more interesting / insightful is the delta between his nightly ppg and excess ppg. Klay only averages 1.34 free throw attempts per game compared to Harden who's averaging ~10. I'll concede that circumstances and roles are a big driver of the gap as a player who's always attacking and has the ball in his hands (Harden) is naturally going to get more calls than a three and D floor spacer. But, Klay is masterfully efficienct. He's able to put up nearly ~20 points per game with barely any reliance on the free-throw line. The next two closest scorers are Khris Middleton and T.J. Warren, both of which average 3.28 and 2.92 times more free throw attempts than Klay, respectively. 